from _typeshed import Incomplete
from semanticscholar.Paper import Paper
from semanticscholar.SemanticScholarObject import (
    SemanticScholarObject as SemanticScholarObject,
)

class Author(SemanticScholarObject):
    FIELDS: Incomplete
    SEARCH_FIELDS = FIELDS
    def __init__(self, data) -> None: ...
    @property
    def affiliations(self) -> list: ...
    @property
    def authorId(self) -> str: ...
    @property
    def citationCount(self) -> int: ...
    @property
    def externalIds(self) -> dict: ...
    @property
    def hIndex(self) -> int: ...
    @property
    def homepage(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def paperCount(self) -> int: ...
    @property
    def papers(self) -> list[Paper]: ...
    @property
    def url(self) -> str: ...
