from semanticscholar.SemanticScholarObject import (
    SemanticScholarObject as SemanticScholarObject,
)

class Journal(SemanticScholarObject):
    def __init__(self, data) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def pages(self) -> str: ...
    @property
    def volume(self) -> int: ...
