from semanticscholar.SemanticScholarObject import (
    SemanticScholarObject as SemanticScholarObject,
)

class PublicationVenue(SemanticScholarObject):
    def __init__(self, data: dict) -> None: ...
    @property
    def alternate_names(self) -> list: ...
    @property
    def alternate_urls(self) -> list: ...
    @property
    def id(self) -> str: ...
    @property
    def issn(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def url(self) -> str: ...
