class SemanticScholarException(Exception):
    def __init__(self, *args: object) -> None: ...

class BadQueryParametersException(SemanticScholarException): ...
class ObjectNotFoundException(SemanticScholarException): ...
class NoMorePagesException(SemanticScholarException): ...
class ServerErrorException(SemanticScholarException): ...
class InternalServerErrorException(ServerErrorException): ...
class GatewayTimeoutException(ServerErrorException): ...
