from typing import Any

class SemanticScholarObject:
    def __init__(self) -> None: ...
    def __getitem__(self, key) -> Any: ...
    def keys(self) -> list: ...
    @property
    def raw_data(self) -> dict: ...
