from pathlib import Path

from _typeshed import Incomplete

SIMPLE_VERSION_REGEX: Incomplete
ILLEGAL_FILENAME_CHARS: str

def shorten_path(path: Path) -> Path: ...
def get_valid_filename(s: str) -> str: ...
def might_be_valid_filename(s: str) -> bool: ...
def simple_version_parse(version: str): ...
def flatten_dict(d: dict): ...
def flatten_filesystem_dict(d): ...
